[workspace]
resolver = "3"
members = ["bin/folio"]

[profile.release]
strip = true
lto = true
opt-level = "s"
codegen-units = 1
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
lto = "off"
opt-level = 3
codegen-units = 1

[workspace.dependencies]
memchr = { version = "2.8.0" }
bytes = { version = "1.11.1" }

# Alloctor
mimalloc = { version = "0.1.50", features = ["secure"] }
